### ISSUE TITLE
각 페이지 확인 및 본인이 하고싶은 페이지 고르기

### ISSUE THREAD

**Issue by sungkuk5420** [sungkuk5420/something-new#23]
- [x] 김성국

- [x] 박재홍

- [x] 박성진

- [x] 서현동

- [x] 이승태

**Comment by sungkuk5420** [comment]
본인이 하고 싶은 페이지 고르신분은 해당 이슈 선택후 오른쪽 Assignees를 눌러 본인을 담당자로 어사인 해주세요.
일단 페이지 하나씩만 고르시면 됩니다.

세트로 묶은 부분들은 디자인이 비슷하여 한사람이 같이 진행하면 좋겠다고 판단되는 페이지들입니다.

페이지 고르신분은 체크박스 체크 후 저를 태그하여 아무댓글이나 남겨주세요.

**Comment by adramnc** [comment]
@sungkuk5420 잘부탁드립니다!!

**Comment by sungkuk5420** [comment]
@adramnc 넵 ㅎㅎㅎ 제가 얼른 시작준비해서 연락드릴게요! 작업가능하신날 카톡연락주세용!

**Comment by tottannim** [comment]
@sungkuk5420 잘부탁드립니다!

**Comment by sungkuk5420** [comment]
@tottannim 넵 저야말로 잘부탁드립니다 !!

**Comment by sungkuk5420** [comment]
이주열은 퍼블리싱이 아닌 기능개발에 투입될예정이니 위의 목록에서 제거하겠습니다
